### ISSUE TITLE
Submod Updater not working properly with the mod

### ISSUE THREAD

**Issue by my-otter-self** [zer0fixer/MAS-Extraplus#3]
`[2022-07-02 13:33:05] [info]: [SUBMOD UPDATER PLUGIN ERROR]: Missing update JSON data, or update url is incorrect. Submod: 'Extra Plus'.
`

**Comment by zer0fixer** [comment]
> `[2022-07-02 13:33:05] [info]: [SUBMOD UPDATER PLUGIN ERROR]: Missing update JSON data, or update url is incorrect. Submod: 'Extra Plus'. `

Several people have already reported this error to me, and that is why I have not updated the submod to see what happens. Although to be honest, I don't know what causes it, it says that the error is because it did not find the url of the submod. I feel that the name of the repository is the problem. I would have to rename it to **MASExtraPlus** without using the **-**

**Comment by dreamscached** [comment]
You're missing a distribution package in your [latest release](https://github.com/zer0fixer/MAS-Extraplus/releases/tag/1.0.2). Look into [source](https://github.com/Booplicate/MAS-Submods-SubmodUpdaterPlugin/blob/1c33faa7c3482d7ae26252911d2e33c5df26b3f3/Submod%20Updater%20Plugin/game/Submods/Submod%20Updater%20Plugin/submod_updater_plugin.rpy#L1095), that's why it keeps giving you that error.

**Comment by my-otter-self** [comment]
fixed it! thanks @dreamscached as always <3
